import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="min-h-screen flex flex-col">
          <header className="sticky top-0 z-10 border-b border-zinc-200 bg-white/80 backdrop-blur">
            <div className="mx-auto flex max-w-6xl items-center gap-3 px-6 py-4">
              <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-zinc-900 text-white">
                AI
              </div>
              <div className="leading-tight">
                <div className="text-sm font-semibold text-zinc-900">
                  AI Practice v2
                </div>
                <div className="text-xs text-zinc-600">
                  Tailwind + Ant Design demo
                </div>
              </div>
            </div>
          </header>

          <div className="mx-auto flex w-full max-w-6xl flex-1">
            <Sidebar />
            <main className="flex-1 h-[calc(100vh-120px)] overflow-auto p-6">
              <section className="mx-auto h-full w-full max-w-6xl rounded-2xl border border-zinc-200 bg-white/70 p-8 shadow-xs">
                {children}
              </section>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
