import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Sidebar from "./components/Sidebar";
import AuthGuard from "./components/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <AntdRegistry>
          <AuthGuard>
            <div className="min-h-screen flex flex-col">
              <header className="sticky top-0 z-10 border-b border-zinc-200 backdrop-blur">
                <div className="mx-auto flex max-w-6xl items-center gap-3 px-6 py-4">
                  <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-zinc-900 text-white">
                    AI
                  </div>
                  <div className="leading-tight">
                    <div className="text-sm font-semibold text-zinc-900">
                      AI Practice v2
                    </div>
                  </div>
                </div>
              </header>

              <div className="mx-auto flex w-full max-w-6xl flex-1 min-h-0">
                <Sidebar />
                <main className="flex-1 min-w-0 p-4 md:p-6">
                  <section className="mx-auto w-full max-w-6xl rounded-2xl border border-zinc-200 p-4 md:p-8 shadow-xs">
                    {children}
                  </section>
                </main>
              </div>
            </div>
          </AuthGuard>
        </AntdRegistry>
      </body>
    </html>
  );
}
